sudo: required
language: node_js
node_js:
  - "4.2"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
install:
  - travis_wait pip install scipy
  - travis_wait pip install pysam
  - pip install .